### ISSUE TITLE
Insufficient documentation

### ISSUE THREAD

**Issue by Sboursen** [Nemwel-Boniface/signature-fx#2]
### Hi @Nemwel-Boniface, :wave: 

First I want to congratulate you this great work that you have done. You not only showed your skills as a front end developer, but also as designer too.

- [x] In order to make you project complete, I suggest that you add a README file that documents your project.

Cool website!

**Comment by Nemwel-Boniface** [comment]
## Hello @Sboursen :wave:

Thank you very much for your kind sentiments! I will make sure to include the README.md file today.

#happycoding
